version: "3"

services:
  cli:
    build: ./docker/cli
    volumes:
      - ./todo:/var/www
    working_dir: /var/www
    links:
      - mysql
  fpm:
    build: ./docker/fpm
    volumes:
      - ./todo:/var/www
      - ./docker/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    working_dir: /var/www
  nginx:
    image: nginx:1.17
    volumes:
      - ./todo:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    links:
      - fpm
    ports:
      - 8000:80
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoapp
      MYSQL_USER: todoapp
      MYSQL_PASSWORD: secret
  selenium:
    image: selenium/standalone-chrome:4.0.0-alpha-7-prerelease-20200921
    depends_on:
      - nginx
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5901:5900
  selenium-recorder:
    image: selenium/video:ffmpeg-4.3.1-20200921
    volumes:
      - ./videos:/videos

volumes:
  mysql_data: ~
